package com.coding.task.common.enums;

public enum ExecutionState {

    PENDING_FOR_EXECUTION,
    PAYMENT_EXECUTION_CLAIMED,
    REQUESTING_FOR_PAYMENT,
    PAYMENT_REQUEST_TIMEOUT,
    PAYMENT_REQUEST_TECHNICAL_FAILED,
    PAYMENT_REQUEST_UNRECOVERABLE_FAILED,
    RESULT_RECEIVED,
    RESPONSE_SENDING_EXECUTION_CLAIMED,
    RESPONSE_SENT,
    RESPONSE_SENDING_TIMEOUT,
    RESPONSE_SENDING_TECHNICAL_FAILED,
    RESPONSE_SENDING_UNRECOVERABLE_FAILED

}
